name: 🚀 Release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - ci/release-pypi
  release:
    types:
      - published

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: hynek/build-and-inspect-python-package@v2

  publish-to-testpypi:
    needs: [dist]
    environment:
      name: testpypi
      url: https://test.pypi.org/p/EEmiLib
    permissions:
      id-token: write
      attestations: write
      contents: read
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: Packages
          path: dist

      - name: Generate artifact attestation for sdist and wheel
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: "dist/*"

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
